version: '3.8'

services:
  tg_redis:
    image: redis:7-alpine

  tg_db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    ports:
      - "5432:5432"
    volumes:
      - tg_pgdata:/var/lib/postgresql/data

  tg_pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      TZ: ${TZ}
    ports:
      - "5050:80"
    volumes:
      - tg_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - tg_db


  tg_backend:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8015 --reload
    volumes:
      - ./backend/app:/app/app
    environment:
      - TZ=${TZ}
      - SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL}
      - LOG_PATH=/app/app/app.log
    depends_on:
      - tg_db
      - tg_redis
    ports:
      - "8015:8015"

  tg_celery_worker:
    build:
      context: ./backend
    command: celery -A app.celery_app.celery worker --loglevel=info
    volumes:
      - ./backend/app:/app/app
    environment:
      - TZ=${TZ}
      - SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL}
    depends_on:
      - tg_backend
      - tg_redis

  tg_celery_beat:
    build:
      context: ./backend
    command: celery -A app.celery_app.celery beat --loglevel=info
    volumes:
      - ./backend/app:/app/app
    environment:
      - TZ=${TZ}
      - SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL}
    depends_on:
      - tg_backend
      - tg_redis

  tg_flower:
    build:
      context: ./backend
    working_dir: /app
    command: >
      celery --app=app.celery_app.celery
             --broker=redis://tg_redis:6379/0
             flower
    environment:
      - TZ=${TZ}
      - FLOWER_PORT=5555
      - FLOWER_BASIC_AUTH=admin:admin
    ports:
      - "5555:5555"
    depends_on:
      - tg_redis
    volumes:
      - ./backend/app:/app/app

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    # command: ["npm", "run", "dev"]
    ports:
      - "5173:80"
    depends_on:
      - tg_backend




volumes:
  tg_pgdata:
  tg_pgadmin_data:
