version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tgmanager
      POSTGRES_USER: tguser
      POSTGRES_PASSWORD: tgpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql+psycopg2://tguser:tgpass@db:5432/tgmanager
      - LOG_PATH=/app/app/app.log
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  celery_worker:
    build: .
    command: celery -A app.celery_app.celery worker --loglevel=info
    volumes:
      - ./app:/app/app
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql+psycopg2://tguser:tgpass@db:5432/tgmanager
    depends_on:
      - backend
      - redis

  celery_beat:
    build: .
    command: celery -A app.celery_app.celery beat --loglevel=info
    volumes:
      - ./app:/app/app
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql+psycopg2://tguser:tgpass@db:5432/tgmanager
    depends_on:
      - backend
      - redis

  flower:
    build: .
    command: flower -A app.celery_app.celery --port=5555
    volumes:
      - ./app:/app/app
    ports:
      - "5555:5555"
    depends_on:
      - redis

volumes:
  pgdata:
